# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

post_install do |installer|
    myTargets = ['Socket.IO-Client-Swift']
    
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end

target 'Dino' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Dino
  pod 'Socket.IO-Client-Swift'

  target 'DinoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMockito'
    pod 'OCMock', '~> 3.4.1'
  end

end
